config/routes.rb
Lingo::Application.routes.draw do

  devise_for :users

  namespace "admin" do
    resources :languages, :shallow => true  do
      member do
        post 'update_level_numbers'
      end
      resources :levels do
        member do
          get 'test'
        end
        resources :sentences, :except => [:show]
        resources :vocabs, :except => [:show], :path => 'vocab'
      end
    end
  end

  match '/games' => 'game#index', :as => 'games'

  resources :game, :except => [:edit, :update] do
    resources :level, :only => [:show] do
      member do
        get 'challenge'
        post 'success'
      end
    end
  end

  root :to => "game#home"

end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :games
  has_many :levels

  scope :enabled, where("enabled = ?", true)

  def enabled?
    self.enabled
  end

  def update_level_numbers
    self.levels.sort.each_with_index do |level, index|
      level.number = index + 1
      level.save
    end
  end

end

app/controllers/admin/languages_controller.rb
class Admin::LanguagesController < Admin::AdminController

  # GET /languages
  # GET /languages.xml
  def index
    @languages = Language.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @languages }
    end
  end

  # GET /languages/1
  # GET /languages/1.xml
  def show
    @language = Language.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @language }
    end
  end

  # GET /languages/new
  # GET /languages/new.xml
  def new
    @language = Language.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @language }
    end
  end

  # GET /languages/1/edit
  def edit
    @language = Language.find(params[:id])
  end

  # POST /languages
  # POST /languages.xml
  def create
    @language = Language.new(params[:language])

    respond_to do |format|
      if @language.save
        format.html { redirect_to(['admin', @language], :notice => 'Language was successfully created.') }
        format.xml  { render :xml => @language, :status => :created, :location => @language }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /languages/1
  # PUT /languages/1.xml
  def update
    @language = Language.find(params[:id])

    respond_to do |format|
      if @language.update_attributes(params[:language])
        format.html { redirect_to(['admin', @language], :notice => 'Language was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update_level_numbers
    params[:ids].each_with_index do |id, index|
      level = Level.find(id)
      level.number = index + 1
      level.save
    end
    render :nothing => true
  end

  # DELETE /languages/1
  # DELETE /languages/1.xml
  def destroy
    @language = Language.find(params[:id])
    @language.destroy

    respond_to do |format|
      format.html { redirect_to(admin_languages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/admin/languages/_form.html.haml
= form_for ['admin', @language] do |f|
  -if @language.errors.any?
    #error_explanation
      %h2= "#{pluralize(@language.errors.count, "error")} prohibited this language from being saved:"
      %ul
        - @language.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :enabled
    = f.check_box :enabled
  .actions
    = f.submit 'Save'

app/views/admin/languages/edit.html.haml
%h1 Editing language

= render 'form'

= link_to 'Show', ['admin', @language]
\|
= link_to 'Back', admin_languages_path

app/views/admin/languages/index.html.haml
%h1 Listing languages

%table
  %tr
    %th Enabled?
    %th Name
    %th
    %th
    %th

  - @languages.each do |language|
    %tr
      %td
        - if language.enabled?
          &#10004;
        - else
          &#10007;
      %td= language.name
      %td= link_to 'Show', ['admin', language]
      %td= link_to 'Edit', edit_admin_language_path(language)
      %td= link_to 'Destroy', ['admin', language], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Language', new_admin_language_path

app/views/admin/languages/new.html.haml
%h1 New language

= render 'form'

= link_to 'Back', admin_languages_path

app/views/admin/languages/show.html.haml
%p
  %b Language:
  = @language.name

%h1 Listing levels

%table#levels
  - @language.levels.sort.each do |level|
    %tr.level{ :id => level.id }
      %td
        %b
          Level
          %span.number= level.number
      %td
        = level.name
        - if level.is_vocab
          %i 
            %b (vocab)
      %td= link_to 'Show', ['admin', level]
      %td= link_to 'Test', test_admin_level_path(level)
      %td= link_to 'Edit', edit_admin_level_path(level)
      %td= link_to 'Destroy', ['admin', level], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'Back to all Languages', admin_languages_path
\|
= link_to 'Edit Language', edit_admin_language_path(@languages)
\|
= link_to 'New Level', new_admin_language_level_path(@language)

:javascript
  $(function() {
    $('#levels').sortable({
      items: '.level',
      update: function(event, ui) {
        var order = $('.level').map(function() {
          return $(this).attr('id');
        }).get();
        $.ajax({
          type: 'post',
          url: '#{update_level_numbers_admin_language_path(@language)}',
          data: { ids: order },
          success: function() {
            $('.level').each(function(index) {
              $(this).find('.number').text(index + 1);
            });
          }
        });
      }
    });
  });