config/routes.rb
Lingo::Application.routes.draw do

  devise_for :users

  namespace "admin" do
    resources :languages, :shallow => true  do
      member do
        post 'update_level_numbers'
      end
      resources :levels do
        member do
          get 'test'
        end
        resources :sentences, :except => [:show]
        resources :vocabs, :except => [:show], :path => 'vocab'
      end
    end
  end

  match '/games' => 'game#index', :as => 'games'

  resources :game, :except => [:edit, :update] do
    resources :level, :only => [:show] do
      member do
        get 'challenge'
        post 'success'
      end
    end
  end

  root :to => "game#home"

end

app/models/vocab.rb
class Vocab < ActiveRecord::Base
  belongs_to :level

  validates_presence_of :english, :foreign
end

app/controllers/admin/vocabs_controller.rb
class Admin::VocabsController < Admin::AdminController

  before_filter :only => [:index, :new, :create] do
    @level = Level.find(params[:level_id])
  end

  # GET /vocabs
  # GET /vocabs.xml
  def index
    redirect_to @level
    #@vocabs = Vocab.all

    #respond_to do |format|
      #format.html # index.html.erb
      #format.xml  { render :xml => @vocabs }
    #end
  end

  ## GET /vocabs/1
  ## GET /vocabs/1.xml
  #def show
  #  @vocab = Vocab.find(params[:id])
  #
  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.xml  { render :xml => @vocab }
  #  end
  #end

  # GET /vocabs/new
  # GET /vocabs/new.xml
  def new
    @vocab = Vocab.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vocab }
    end
  end

  # GET /vocabs/1/edit
  def edit
    @vocab = Vocab.find(params[:id])
  end

  # POST /vocabs
  # POST /vocabs.xml
  def create
    @vocab = Vocab.new(params[:vocab])
    @vocab.level = @level

    respond_to do |format|
      if @vocab.save
        format.html { redirect_to(new_admin_level_vocab_path(@level), :notice => 'Vocab was successfully created.') }
        format.xml  { render :xml => @vocab, :status => :created, :location => @vocab }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vocab.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vocabs/1
  # PUT /vocabs/1.xml
  def update
    @vocab = Vocab.find(params[:id])
    @level = @vocab.level

    respond_to do |format|
      if @vocab.update_attributes(params[:vocab])
        format.html { redirect_to(['admin', @level], :notice => 'Vocab was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vocab.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabs/1
  # DELETE /vocabs/1.xml
  def destroy
    @vocab = Vocab.find(params[:id])
    @level = @vocab.level
    @vocab.destroy

    respond_to do |format|
      format.html { redirect_to(['admin', @level]) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/vocabs_helper.rb
module VocabsHelper
end

app/views/admin/vocabs/_form.html.haml
= form_for path do |f|
  -if @vocab.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vocab.errors.count, "error")} prohibited this vocab from being saved:"
      %ul
        - @vocab.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :english
    = f.text_field :english
  .field
    = f.label :foreign
    = f.text_field :foreign
  .actions
    = f.submit 'Save'

- content_for :javascripts do
  :javascript
    var $j = jQuery;

    $j(function() {
      $j('#vocab_english').focus();
    });

app/views/admin/vocabs/edit.html.haml
%p
  %b Language:
  = @vocab.level.language.name
  %b Level:
  = @vocab.level.name

%h1 Editing vocab

= render :partial => 'form', :locals => { :path => ['admin', @vocab] }

= link_to "Back to #{@vocab.level.name}", ['admin', @vocab.level]
\|
= link_to 'Show', ['admin', @vocab]

app/views/admin/vocabs/new.html.haml
%p
  %b Language:
  = @level.language.name
  %b Level:
  = @level.name

%h1 New vocab

= render :partial => 'form', :locals => { :path => ['admin', @level, @vocab] }

= link_to "Back to #{@level.name}", ['admin', @level]

app/views/admin/vocabs/show.html.haml
%p
  %b Language:
  = @level.language.name
  %b Level:
  = @level.name

%h1 Listing vocabs

%table
  %tr
    %th
    %th English
    %th Foreign
    %th
    %th
    %th

  - @level.vocabs.each_with_index do |vocab, index|
    %tr
      %td= "#{index + 1}."
      %td= vocab.english
      %td= vocab.foreign
      -#%td= link_to 'Show', [@level, vocab]
      %td= link_to 'Edit', edit_admin_vocab_path(vocab)
      %td= link_to 'Destroy', ['admin', vocab], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'Back to all Levels', ['admin', @level.language]
\|
= link_to 'Edit Level', edit_admin_level_path(@level)
\|
= link_to 'Test', test_admin_level_path(@level)
\|
= link_to 'New Vocab', new_admin_level_vocab_path(@level)