config/routes.rb
Lingo::Application.routes.draw do

  devise_for :users

  namespace "admin" do
    resources :languages, :shallow => true  do
      member do
        post 'update_level_numbers'
      end
      resources :levels do
        member do
          get 'test'
        end
        resources :sentences, :except => [:show]
        resources :vocabs, :except => [:show], :path => 'vocab'
      end
    end
  end

  match '/games' => 'game#index', :as => 'games'

  resources :game, :except => [:edit, :update] do
    resources :level, :only => [:show] do
      member do
        get 'challenge'
        post 'success'
      end
    end
  end

  root :to => "game#home"

end

app/models/level.rb
class Level < ActiveRecord::Base

  belongs_to :language

  has_many :sentences
  has_many :vocabs

  def is_vocab?
    self.is_vocab
  end

  def vocab
    self.vocabs
  end

  include Comparable   
  def <=> other
    return 0 if !self.number && !other.number
    return 1 if !self.number
    return -1 if !other.number
    self.number <=> other.number
  end

end

app/controllers/admin/levels_controller.rb
class Admin::LevelsController < Admin::AdminController

  # GET /levels
  # GET /levels.xml
  def index
    redirect_to admin_language_path(params[:language_id])
    #@levels = Level.all

    #respond_to do |format|
      #format.html # index.html.erb
      #format.xml  { render :xml => @levels }
    #end
  end

  # GET /levels/1
  # GET /levels/1.xml
  def show
    @level = Level.find(params[:id])

    respond_to do |format|
      format.html {
        if @level.is_vocab?
          render 'admin/vocabs/show'
        else
          render 'admin/sentences/show'
        end
      }
      format.xml  { render :xml => @level }
    end
  end

  def test
    @level = Level.find(params[:id])

    if @level.is_vocab?
      @testing = @level.vocab
    else
      @testing = @level.sentences
    end
  end

  # GET /levels/new
  # GET /levels/new.xml
  def new
    @level = Level.new
    @language = Language.find(params[:language_id])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @level }
    end
  end

  # GET /levels/1/edit
  def edit
    @level = Level.find(params[:id])
  end

  # POST /levels
  # POST /levels.xml
  def create
    @level = Level.new(params[:level])
    @language = Language.find(params[:language_id])

    @level.language = @language

    respond_to do |format|
      if @level.save
        @language.update_level_numbers
        format.html { redirect_to(['admin', @level], :notice => 'Level was successfully created.') }
        format.xml  { render :xml => @level, :status => :created, :location => @level }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @level.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /levels/1
  # PUT /levels/1.xml
  def update
    @level = Level.find(params[:id])
    @language = @level.language

    respond_to do |format|
      if @level.update_attributes(params[:level])
        format.html { redirect_to(['admin', @level], :notice => 'Level was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @level.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.xml
  def destroy
    level = Level.find(params[:id])
    level.destroy
    @language = level.language
    @language.update_level_numbers

    respond_to do |format|
      format.html { redirect_to(['admin', @language]) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/level_controller.rb
class LevelController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_game_and_level

  def show
    authorize! :show, @level, @game
  end

  def challenge
    if @level.is_vocab?
      @testing = @level.vocab
    else
      @testing = @level.sentences
    end

    authorize! :challenge, @level, @game
  end

  def success
    authorize! :challenge, @level, @game

    if @game.current_level == @level
      if @game.has_next_level?
        @game.goto_next_level
        flash[:notice] = 'Next level unlocked!'
      else
        # TODO could just be playing last level
        flash[:notice] = 'Game complete - congrats!'
      end
    end

    redirect_to @game
  end

  protected

  def load_game_and_level
    @game = Game.find(params[:game_id])
    @level = Level.find(params[:id])
  end

end

app/helpers/level_helper.rb
module LevelHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/index.html.haml
%h1 Listing levels

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @levels.each do |level|
    %tr
      %td
        = level.name
        - if level.is_vocab
          %i 
            %b (vocab)
      %td= link_to 'Show', level
      %td= link_to 'Test', test_level_path(level)
      %td= link_to 'Edit', edit_level_path(level)
      %td= link_to 'Destroy', level, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Level', new_level_path

app/views/levels/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @level.name

%h1 Listing sentences

%table
  %tr
    %th English
    %th Foreign
    %th
    %th
    %th

  - @level.sentences.each do |sentence|
    %tr
      %td= sentence.english
      %td= sentence.foreign
      %td= link_to 'Show', [@level, sentence]
      %td= link_to 'Edit', edit_level_sentence_path(@level, sentence)
      %td= link_to 'Destroy', [@level, sentence], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'Back to all Levels', levels_path
\|
= link_to 'Edit Level', edit_level_path(@level)
\|
= link_to 'Test', test_level_path(@level)
\|
= link_to 'New Sentence', new_level_sentence_path(@level)