config/routes.rb
Lingo::Application.routes.draw do

  devise_for :users

  namespace "admin" do
    resources :languages, :shallow => true  do
      member do
        post 'update_level_numbers'
      end
      resources :levels do
        member do
          get 'test'
        end
        resources :sentences, :except => [:show]
        resources :vocabs, :except => [:show], :path => 'vocab'
      end
    end
  end

  match '/games' => 'game#index', :as => 'games'

  resources :game, :except => [:edit, :update] do
    resources :level, :only => [:show] do
      member do
        get 'challenge'
        post 'success'
      end
    end
  end

  root :to => "game#home"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Linguo
    = stylesheet_link_tag 'scaffold', 'linguo'
    = yield :stylesheets
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js", :type => "text/javascript"}
    = javascript_include_tag :defaults
    = yield :javascripts
    = csrf_meta_tag
  %body

    #container

      #header
        .links
          - if user_signed_in?
            = link_to 'My Games', games_path
            = link_to 'New Game', new_game_path
            = link_to 'Admin', admin_languages_path if current_user.admin?
            = link_to 'Signout', destroy_user_session_path
          - else
            = link_to 'Signin', new_user_session_path
            = link_to 'Signup', new_user_registration_path
        %h1 Linguo

      #content
        %p#notice.notice= notice
        %p#alert.alert= alert

        = yield

      #footer